// Isolated installation and actual execution checks; no user project, service or model.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { PACKAGE_ROOT, planInstall, applyPlan, planUninstall, STATE, DEFAULT_SKILL, doctor } from '../scripts/project-install.mjs';
import { VERSION, header, inventory } from '../scripts/lib.mjs';
import { specRef } from '../scripts/contract.mjs';
import { fixture, makeDoc, record, approved, FILE } from './fixtures.mjs';
import { checkDelivery } from '../scripts/delivery.mjs';
function target(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ddd-upgrade-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return root;}
function cli(root,flags=[]){return spawnSync(process.execPath,[path.join(PACKAGE_ROOT,'scripts/upgrade.mjs'),root,...flags],{encoding:'utf8'});}
test('explicit upgrade entry previews without writing or implying documents migrated',t=>{const root=target(t);fs.writeFileSync(path.join(root,'AGENTS.md'),'Original');const r=cli(root,['--json']);assert.equal(r.status,0,r.stderr);const p=JSON.parse(r.stdout);assert.equal(p.entrypoint,'upgrade');assert.equal(p.applied,false);assert.equal(p.documents.migration,'not-run');assert.equal(fs.readFileSync(path.join(root,'AGENTS.md'),'utf8'),'Original');assert.ok(!fs.existsSync(path.join(root,'.doc-driven.json')));});
test('upgrade entry applies, reports actual version and preserves all original prose',t=>{const root=target(t),raw='\uFEFF# 原规范\r\n不能覆盖\n末行';fs.writeFileSync(path.join(root,'AGENTS.md'),raw);const r=cli(root,['--apply','--json']);assert.equal(r.status,0,r.stderr);const x=JSON.parse(r.stdout);assert.equal(x.sourceVersion,VERSION);assert.equal(x.doctor.installedVersion,VERSION);assert.equal(x.documents.action,'preserved');assert.equal(x.doctor.runtime,'not-run');assert.ok(fs.readFileSync(path.join(root,'AGENTS.md'),'utf8').startsWith(raw));});
test('same local version is not presented as a newly discovered upgrade',t=>{const root=target(t);applyPlan(planInstall(root,{host:'agents'}));const r=cli(root,['--apply','--json']);assert.equal(r.status,0,r.stderr);const x=JSON.parse(r.stdout);assert.equal(x.previousVersion,VERSION);assert.equal(x.versionChanged,false);assert.equal(x.result.changed,0);});
test('downgrade refused without changing rules or receipt',t=>{const root=target(t);applyPlan(planInstall(root,{host:'agents'}));const state=JSON.parse(fs.readFileSync(path.join(root,STATE)));state.version='99.0.0';fs.writeFileSync(path.join(root,STATE),JSON.stringify(state));const before=fs.readFileSync(path.join(root,STATE));assert.throws(()=>planInstall(root),/Refusing downgrade/);assert.deepEqual(fs.readFileSync(path.join(root,STATE)),before);});
test('locally modified project skill is not overwritten by upgrade alias',t=>{const root=target(t);applyPlan(planInstall(root,{host:'agents'}));const p=path.join(root,DEFAULT_SKILL,'SKILL.md');fs.appendFileSync(p,'\nPersonal customization\n');const before=fs.readFileSync(p);const r=cli(root,['--apply']);assert.equal(r.status,2);assert.deepEqual(fs.readFileSync(p),before);});
test('project documents and custom config are untouched by upgrade/reinstall',t=>{const root=target(t);fs.mkdirSync(path.join(root,'design'));const raw='{ "schemaVersion": 1, "enabled": true, "docsRoots": ["design"], "index": "design/index.md", "layout": "preserve" }';fs.writeFileSync(path.join(root,'.doc-driven.json'),raw);fs.writeFileSync(path.join(root,'design/user.md'),'# Personal design\nDo not migrate this\n');const r=cli(root,['--apply']);assert.equal(r.status,0,r.stderr);assert.equal(fs.readFileSync(path.join(root,'.doc-driven.json'),'utf8'),raw);assert.equal(fs.readFileSync(path.join(root,'design/user.md'),'utf8'),'# Personal design\nDo not migrate this\n');});
test('uninstall retains user prose added outside the upgraded managed block',t=>{const root=target(t);fs.writeFileSync(path.join(root,'AGENTS.md'),'# Original\n');applyPlan(planInstall(root,{host:'agents'}));fs.appendFileSync(path.join(root,'AGENTS.md'),'\nLater human rule\n');const r=cli(root,['--apply']);assert.equal(r.status,0,r.stderr);applyPlan(planUninstall(root));assert.match(fs.readFileSync(path.join(root,'AGENTS.md'),'utf8'),/Later human rule/);});
test('short rule block routes to skill upgrade and sustained execution without duplicated guides',t=>{const root=target(t);applyPlan(planInstall(root,{host:'agents'}));const s=fs.readFileSync(path.join(root,'AGENTS.md'),'utf8'),entry=fs.readFileSync(path.join(root,DEFAULT_SKILL,'SKILL.md'),'utf8');for(const phrase of ['SKILL.md','UPGRADE.md','同一方案已确认则继续','SKIP'])assert.ok(s.includes(phrase),phrase);for(const guide of ['EXECUTION.md','ORCHESTRATION.md','COMMUNICATION.md'])assert.ok(entry.includes(guide),guide);assert.equal(doctor(root).activation,'ready');});
test('identity and optional delivery commands have executable help without project writes',t=>{const root=target(t);for(const name of ['upgrade','delivery']){const r=spawnSync(process.execPath,[path.join(PACKAGE_ROOT,`scripts/${name}.mjs`),'--help'],{cwd:root,encoding:'utf8'});assert.equal(r.status,0,r.stderr);}assert.deepEqual(fs.readdirSync(root),[]);});

// This is a REAL isolated program invocation, distinct from synthetic permission fixtures.
test('real runtime path fails while unused component works, passes only after wiring',t=>{
  const f=fixture(t);f.put('src/main.mjs','export const add=(a,b)=>a+b;\n');f.put('src/app.mjs','export function run(){ return null; }\n');
  const unit=spawnSync(process.execPath,['--input-type=module','-e',"import assert from 'node:assert/strict'; import {add} from './src/main.mjs'; assert.equal(add(7,2),9); console.log('component passed');"],{cwd:f.root,encoding:'utf8'});assert.equal(unit.status,0,unit.stderr);
  const command=[process.execPath,'--input-type=module','-e',"import assert from 'node:assert/strict'; import {run} from './src/app.mjs'; assert.equal(run(7,2),9); console.log('runtime accepted: 7+2=9');"];
  const broken=spawnSync(command[0],command.slice(1),{cwd:f.root,encoding:'utf8'});assert.notEqual(broken.status,0);
  f.put('.doc-driven/runs/broken.log',broken.stdout+broken.stderr);
  const before=makeDoc({...approved,Baseline:f.baseline(),Verification:'not-run'});f.save({...before,text:before.text+record(before,f.baseline(),{Level:'acceptance',Executed:'1',Skipped:'0',Failed:'0',Artifact:'.doc-driven/runs/broken.log',Result:'failed',Environment:`${process.platform}, Node ${process.version}`,Method:JSON.stringify(command),Detail:'Actual runtime assertion failed; component alone passed.'})});
  const p={kind:'ddd-delivery-v1',schemaVersion:1,title:'真实隔离程序入口接线',authorization:{mode:'implement',source:'Synthetic authorization for actual local fixture, not a human approval',specRefs:[specRef(before)]},units:[{name:'计算 / 正式入口 / 求和结果',outcome:'调用 run(7,2) 得到 9',covers:['R-MAIN-001'],state:'done',writePaths:['src/**'],integration:'required',entryPoints:['src/app.mjs'],runtimePath:'run -> add -> numeric result',requiredLevels:['integration','acceptance'],evidence:['E-MAIN-001'],codeBaseline:f.baseline()}]};
  const save=()=>f.put('docs/changes/live.md','# Current\n<!-- ddd:delivery -->\n```json\n'+JSON.stringify(p)+'\n```\n');save();assert.ok(checkDelivery(f.root,f.config,'docs/changes/live.md',{complete:true}).errors.length);
  f.put('src/app.mjs',"import {add} from './main.mjs'; export function run(a,b){return add(a,b);}\n");
  const executed=spawnSync(command[0],command.slice(1),{cwd:f.root,encoding:'utf8'});assert.equal(executed.status,0,executed.stderr);assert.match(executed.stdout,/runtime accepted/);f.put('.doc-driven/runs/passed.log',executed.stdout);
  const now=makeDoc({...approved,Baseline:f.baseline(),Verification:'passed'});
  const fields={Executed:'1',Skipped:'0',Failed:'0',Artifact:'.doc-driven/runs/passed.log',Environment:`${process.platform}, Node ${process.version}`,Method:JSON.stringify(command),Detail:'One real assertion through run and add returned 9; same actual run provides integration and scenario evidence, not independent executions.'};
  f.save({...now,text:now.text+record(before,before.fields.Baseline,{Result:'failed',id:'E-MAIN-001',...fields,Artifact:'.doc-driven/runs/broken.log',Level:'acceptance',Detail:'Historical failed run before wiring; retained, new code baseline resolves it.'})+record(now,f.baseline(),{...fields,id:'E-MAIN-002',Level:'integration'})+record(now,f.baseline(),{...fields,id:'E-MAIN-003',Level:'acceptance'})});
  p.authorization.specRefs=[specRef(now)];p.units[0].codeBaseline=f.baseline();p.units[0].evidence=['E-MAIN-002','E-MAIN-003'];save();assert.deepEqual(checkDelivery(f.root,f.config,'docs/changes/live.md',{complete:true}).errors,[]);
});
test('doctor routes a managed older version to explicit upgrade entry',t=>{const root=target(t);applyPlan(planInstall(root,{host:'agents'}));const state=JSON.parse(fs.readFileSync(path.join(root,STATE)));state.version='0.2.4';fs.writeFileSync(path.join(root,STATE),JSON.stringify(state));const r=doctor(root);assert.equal(r.next.action,'preview-upgrade');assert.match(r.next.previewArgv[1],/upgrade\.mjs$/);});
