// Real local executions and adversarial record cases; never call models or services.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fixture, makeDoc, approved, FILE } from './fixtures.mjs';
import { specRef } from '../scripts/contract.mjs';
import { sha, loadConfig } from '../scripts/lib.mjs';
import { loadPlan, previewPlan, runVerification, checkRun, receiptEvidence, PACKAGE } from '../scripts/verification.mjs';
import { normalizeJSON, parseFlatTAP, judge } from '../scripts/test-results.mjs';
export const PLAN='docs/changes/sum.verify.json';
export function setup(t){
 const f=fixture(t);f.d=f.save(makeDoc(approved));
 f.put('src/entry.mjs',"import {add} from './main.mjs'; export const run=(a,b)=>add(a,b);\n");
 f.put('tests/entry.test.mjs',"import test from 'node:test';import assert from 'node:assert/strict';import {run} from '../src/entry.mjs';test('user receives sum',()=>assert.equal(run(7,2),9));\n");
 f.p={kind:'ddd-verification-plan-v1',schemaVersion:1,name:'计算 / 正式入口 / 返回结果',authorization:{mode:'verify',source:'Synthetic fixture authorization for real isolated process tests, not a user approval'},specRefs:[specRef(f.d)],environment:{name:'isolated fixture',scope:'isolated',resources:'Only this temporary repository; no network or databases',limitations:'Local behavior only; no production claims'},checks:[{id:'entry',name:'正式入口返回求和',kind:'test',level:'acceptance',covers:['R-MAIN-001'],scenario:'run(7,2) returns 9',command:{executable:'node',args:['--test','--test-reporter={skill}/scripts/node-reporter.mjs','tests/entry.test.mjs'],cwd:'.'},parser:'json-v1',requiredCases:['user receives sum'],inputs:['tests/entry.test.mjs','src/entry.mjs'],timeoutMs:10000}]};
 f.savePlan=()=>f.put(PLAN,JSON.stringify(f.p,null,2)+'\n');f.savePlan();
 f.run=()=>runVerification(f.root,f.config,PLAN,{expectPlan:previewPlan(f.root,f.config,PLAN).planHash});
 f.validate=r=>checkRun(f.root,f.config,r.path);return f;
}
const good=r=>assert.deepEqual(r.errors,[],JSON.stringify(r));
const rejected=r=>assert.ok(r.errors.length,JSON.stringify(r));
test('preview performs no writes or project executions',t=>{const f=setup(t);const before=f.read(FILE);const r=previewPlan(f.root,f.config,PLAN);assert.equal(r.execution,'not-run');assert.equal(f.read(FILE),before);assert.ok(!fs.existsSync(path.join(f.root,'.doc-driven')));});
test('actual entry execution creates current receipt and human-named evidence',async t=>{const f=setup(t);const r=await f.run();assert.equal(r.report.status,'passed',JSON.stringify(r.report));good(f.validate(r));assert.equal(r.report.results[0].counts.executed,1);const text=receiptEvidence(f.root,f.config,r.path);assert.match(text,/Runner-Receipt:/);assert.match(text,/正式入口返回求和/);f.put(FILE,f.read(FILE)+text);good(f.validate(r));});
test('component green cannot cover disconnected actual entry',async t=>{const f=setup(t);f.put('src/entry.mjs','export const run=()=>null;\n');const component=spawnSync(process.execPath,['--input-type=module','-e',"import assert from 'node:assert/strict';import {add} from './src/main.mjs';assert.equal(add(7,2),9)"],{cwd:f.root});assert.equal(component.status,0);const bad=await f.run();assert.equal(bad.report.status,'failed');rejected(f.validate(bad));f.put('src/entry.mjs',"import {add} from './main.mjs';export const run=add;\n");const fixed=await f.run();assert.equal(fixed.report.status,'passed');good(f.validate(fixed));assert.ok(fs.existsSync(path.join(f.root,bad.path)));});
test('reviewed plan digest required before any process or artifact write',async t=>{const f=setup(t);await assert.rejects(runVerification(f.root,f.config,PLAN,{expectPlan:'old'}),/expect-plan/);assert.ok(!fs.existsSync(path.join(f.root,'.doc-driven')));});
for(const mode of ['design-only','hold'])test(`${mode} cannot authorize execution`,async t=>{const f=setup(t);f.p.authorization.mode=mode;f.savePlan();await assert.rejects(f.run(),/does not authorize/);assert.ok(!fs.existsSync(path.join(f.root,'.doc-driven')));});
test('disabled workflow fails rather than skipped pass',t=>{const f=setup(t);assert.throws(()=>previewPlan(f.root,{...f.config,enabled:false},PLAN),/disabled/);});
test('missing required environment recorded blocked without launching code',async t=>{const f=setup(t);f.p.checks[0].requiresEnv=['DDD_TEST_UNSET_FOR_REQUIRED_ENV']; // DDD_ is reserved: use ordinary name
 f.p.checks[0].requiresEnv=['TEST_UNSET_REQUIRED_ENV_ABC'];delete process.env.TEST_UNSET_REQUIRED_ENV_ABC;f.savePlan();const r=await f.run();assert.equal(r.report.status,'blocked');assert.equal(r.report.results[0].process,null);rejected(f.validate(r));});
test('SKIP plus exit zero does not pass required scenario',async t=>{const f=setup(t);f.put('tests/entry.test.mjs',"import test from 'node:test';test('user receives sum',{skip:'DATABASE_URL missing'},()=>{});\n");const r=await f.run();assert.equal(r.report.results[0].process.exitCode,0);assert.equal(r.report.status,'failed');assert.equal(r.report.results[0].counts.skipped,1);});
test('TODO is not proof of a passing required scenario',async t=>{const f=setup(t);f.put('tests/entry.test.mjs',"import test from 'node:test';test.todo('user receives sum');\n");const r=await f.run();assert.equal(r.report.status,'failed');});
test('zero tests cannot pass',async t=>{const f=setup(t);f.put('tests/entry.test.mjs','// No tests\n');const r=await f.run();assert.notEqual(r.report.status,'passed');});
test('different passing test cannot stand in for required named case',async t=>{const f=setup(t);f.put('tests/entry.test.mjs',"import test from 'node:test';test('unrelated scenario',()=>{});\n");assert.equal((await f.run()).report.status,'failed');});
test('an explicit unrelated optional skip is disclosed without blocking required case',async t=>{const f=setup(t);f.put('tests/entry.test.mjs',f.read('tests/entry.test.mjs')+"test.skip('optional external environment',()=>{});\n");f.p.checks[0].optionalCases=['optional external environment'];f.p.checks[0].optionalReason='Not in this local behavior scope; separate external check';f.savePlan();const r=await f.run();assert.equal(r.report.status,'passed');assert.equal(r.report.results[0].counts.skipped,1);good(f.validate(r));});
test('optional name cannot suppress an actual failed assertion',async t=>{const f=setup(t);f.put('tests/entry.test.mjs',f.read('tests/entry.test.mjs')+"test('optional case',()=>{throw Error('bad')});\n");f.p.checks[0].optionalCases=['optional case'];f.p.checks[0].optionalReason='May skip if unrelated service absent';f.savePlan();assert.equal((await f.run()).report.status,'failed');});
test('unexpected skipped case needs explicit rationale',async t=>{const f=setup(t);f.put('tests/entry.test.mjs',f.read('tests/entry.test.mjs')+"test.skip('unexpected skip',()=>{});\n");assert.equal((await f.run()).report.status,'failed');});
test('duplicate case names are rejected rather than conflated',async t=>{const f=setup(t);f.put('tests/entry.test.mjs',f.read('tests/entry.test.mjs')+"test('user receives sum',()=>{});\n");assert.notEqual((await f.run()).report.status,'passed');});
test('native suite emits actual leaf results',async t=>{const f=setup(t);f.put('tests/entry.test.mjs',"import {describe,it} from 'node:test';describe('math',()=>{it('user receives sum',()=>{});});\n");const r=await f.run();assert.equal(r.report.status,'passed',JSON.stringify(r.report));good(f.validate(r));});
for(const type of ['body','revision','code','test','config','plan','rules','input'])test(`${type} change invalidates old evidence`,async t=>{const f=setup(t);if(type==='input'){f.put('.doc-driven/private-input.txt','a');f.p.checks[0].inputs.push('.doc-driven/private-input.txt');f.savePlan();}if(type==='rules')f.put('AGENTS.md','Original');const r=await f.run();assert.equal(r.report.status,'passed');if(type==='body')f.put(FILE,f.read(FILE).replace('sum of','difference of'));if(type==='revision')f.put(FILE,f.read(FILE).replace('Revision: 1','Revision: 2'));if(type==='code')f.put('src/main.mjs','export const add=(a,b)=>a-b;\n');if(type==='test')f.put('tests/entry.test.mjs',f.read('tests/entry.test.mjs')+'\n// changed\n');if(type==='config')f.put('.doc-driven.json',JSON.stringify({...f.config,language:'en'}));if(type==='plan'){f.p.checks[0].scenario+=' changed';f.savePlan();}if(type==='rules')f.put('AGENTS.md','New rule');if(type==='input')f.put('.doc-driven/private-input.txt','b');rejected(f.validate(r));});
test('runner recognizes mutation during a test and does not call it current',async t=>{const f=setup(t);f.put('tests/entry.test.mjs',"import fs from 'node:fs';import test from 'node:test';test('user receives sum',()=>fs.appendFileSync('src/main.mjs','\\n// mutation'));\n");assert.equal((await f.run()).report.status,'stale');});
test('logs and run status cannot be accidentally edited into success',async t=>{const f=setup(t);const r=await f.run();fs.appendFileSync(path.join(f.root,r.report.results[0].artifacts[0].path),'tamper');rejected(f.validate(r));});
test('receipt checksum detects edited counts',async t=>{const f=setup(t);const r=await f.run();f.put(r.path,f.read(r.path).replace('"executed": 1','"executed": 7'));rejected(f.validate(r));});
test('even recomputed checksum cannot make missing output agree with counts',async t=>{const f=setup(t);const r=await f.run();const changed={...r.report};changed.results[0].counts.executed=7;const data=JSON.stringify(changed);f.put(r.path,data);f.put(r.path.replace('run.json','run.sha256'),sha(data));rejected(f.validate(r));});
test('receipt from another plan is refused',async t=>{const f=setup(t),r=await f.run();rejected(checkRun(f.root,f.config,r.path,{plan:'docs/changes/other.json'}));});
test('pinned receipt hash must still match',async t=>{const f=setup(t),r=await f.run();rejected(checkRun(f.root,f.config,r.path,{hash:'f'.repeat(64)}));});
test('plain exit-zero output cannot masquerade as test success',async t=>{const f=setup(t);f.p.checks[0].command.args=['-e',"console.log('all passed')"];f.savePlan();assert.equal((await f.run()).report.status,'failed');});
test('wrong report run nonce cannot reuse old JSON output',async t=>{const f=setup(t);f.p.checks[0].command.args=['-e',`console.log(JSON.stringify({kind:'ddd-test-results-v1',complete:true,runId:'old',cases:[{name:'user receives sum',status:'passed'}]}))`];f.savePlan();assert.notEqual((await f.run()).report.status,'passed');});
test('nonzero exit beats a valid passing JSON report',async t=>{const f=setup(t);f.p.checks[0].command.args=['-e',`console.log(JSON.stringify({kind:'ddd-test-results-v1',complete:true,runId:process.env.DDD_RUN_ID,cases:[{name:'user receives sum',status:'passed'}]}));process.exitCode=1`];f.savePlan();assert.equal((await f.run()).report.status,'failed');});
test('compiler-style check uses exit code without invented case counts',async t=>{const f=setup(t);Object.assign(f.p.checks[0],{kind:'command',level:'static',parser:'exit-code',command:{executable:'node',args:['--check','src/main.mjs']}});delete f.p.checks[0].requiredCases;f.savePlan();const r=await f.run();assert.equal(r.report.status,'passed');assert.equal(r.report.results[0].counts,undefined);assert.equal(receiptEvidence(f.root,f.config,r.path),'');});
test('exit-code command cannot replace acceptance',t=>{const f=setup(t);f.p.checks[0].kind='command';f.p.checks[0].parser='exit-code';f.savePlan();assert.throws(()=>loadPlan(f.root,f.config,PLAN),/cannot stand/);});
test('missing executable is a blocked check, not a pass',async t=>{const f=setup(t);f.p.checks[0].command.executable='not-a-real-tool-7329';f.savePlan();assert.equal((await f.run()).report.status,'blocked');});
test('timeout terminates a real process and records it',async t=>{const f=setup(t);f.p.checks[0].command.args=['-e','setInterval(()=>{},1000)'];f.p.checks[0].timeoutMs=100;f.savePlan();const r=await f.run();assert.equal(r.report.results[0].status,'timed-out');assert.equal(r.report.status,'failed');});
test('bounded output is enforced',async t=>{const f=setup(t);f.p.checks[0].command.args=['-e',"console.log('x'.repeat(4096))"];f.p.checks[0].maxOutputBytes=1024;f.savePlan();const r=await f.run();assert.equal(r.report.results[0].process.reason,'output-limit');assert.ok(fs.statSync(path.join(f.root,r.report.results[0].artifacts[0].path)).size<=1024);});
test('manual acceptance remains explicit rather than automated green',async t=>{const f=setup(t);f.p.checks=[{id:'manual',name:'视觉验收',kind:'manual',level:'acceptance',covers:['R-MAIN-001'],scenario:'Human checks clarity',reason:'Requires human judgment'}];f.savePlan();assert.equal((await f.run()).report.status,'manual-required');});
test('failed dependency blocks dependents but unrelated checks continue',async t=>{const f=setup(t);const c=f.p.checks[0];f.p.checks=[{...c,id:'broken',command:{executable:'node',args:['-e','process.exit(1)']}},{...c,id:'dependent',dependsOn:['broken']},{...c,id:'independent'}];f.savePlan();const r=await f.run();assert.deepEqual(r.report.results.map(x=>x.status),['failed','blocked','passed']);});
test('active lock is preserved and prevents simultaneous runs',async t=>{const f=setup(t);f.put('.doc-driven/verification.lock','another active process');await assert.rejects(f.run(),/lock/);assert.equal(f.read('.doc-driven/verification.lock'),'another active process');});
test('symlink output path is refused without touching its target',async t=>{const f=setup(t);fs.mkdirSync(path.join(f.root,'.doc-driven'),{recursive:true});fs.symlinkSync(f.root,path.join(f.root,'.doc-driven/verification'));await assert.rejects(f.run(),/Symbolic links/);assert.ok(!fs.existsSync(path.join(f.root,'runs')));});
test('explicit secret env values are redacted from output and receipt',async t=>{const f=setup(t);process.env.TEST_RUNNER_SECRET='secret-long-value-abc123';t.after(()=>delete process.env.TEST_RUNNER_SECRET);f.p.checks[0].passEnv=['TEST_RUNNER_SECRET'];f.p.checks[0].command.args=['-e',`console.error(process.env.TEST_RUNNER_SECRET);console.log(JSON.stringify({kind:'ddd-test-results-v1',runId:process.env.DDD_RUN_ID,complete:true,cases:[{name:'user receives sum',status:'passed'}]}))`];f.savePlan();const r=await f.run();assert.equal(r.report.status,'passed');assert.doesNotMatch(f.read(r.path),/secret-long-value/);assert.equal(f.read(r.report.results[0].artifacts[1].path).trim(),'[REDACTED]');good(f.validate(r));});
test('unspecified environment secrets are not inherited',async t=>{const f=setup(t);process.env.UNFORWARDED_SECRET='do-not-pass';t.after(()=>delete process.env.UNFORWARDED_SECRET);f.p.checks[0].command.args=['-e',`if(process.env.UNFORWARDED_SECRET)process.exit(1);console.log(JSON.stringify({kind:'ddd-test-results-v1',runId:process.env.DDD_RUN_ID,complete:true,cases:[{name:'user receives sum',status:'passed'}]}))`];f.savePlan();assert.equal((await f.run()).report.status,'passed');});
for(const [field,value] of [['typo',true],['checks',[]],['selectedItems',['R-OTHER-001']]])test(`invalid plan ${field} rejected before writes`,t=>{const f=setup(t);f.p[field]=value;f.savePlan();assert.throws(()=>loadPlan(f.root,f.config,PLAN));assert.ok(!fs.existsSync(path.join(f.root,'.doc-driven')));});
test('omitting a bound requirement cannot pass plan coverage',t=>{const f=setup(t);f.d=f.save(makeDoc(approved,makeDoc().text.split('## 摘要')[1]?'## 摘要\nTest\n### R-MAIN-001 Sum\nAdd\n### R-MAIN-002 Negative\nReject\n':'unused'));f.p.specRefs=[specRef(f.d)];f.savePlan();assert.throws(()=>loadPlan(f.root,f.config,PLAN),/Every selected/);});
test('scope reduction requires recorded authorization source',t=>{const f=setup(t);f.p.selectedItems=['R-MAIN-001'];f.savePlan();assert.throws(()=>loadPlan(f.root,f.config,PLAN),/scopeSource/);});
test('cycles and forward check dependencies rejected',t=>{const f=setup(t);f.p.checks[0].dependsOn=['entry'];f.savePlan();assert.throws(()=>loadPlan(f.root,f.config,PLAN),/Dependencies/);});
test('CLI preview is read only and receipt validation is separate',t=>{const f=setup(t);const p=spawnSync(process.execPath,[path.join(PACKAGE,'scripts/verify.mjs'),f.root,'--plan',PLAN,'--json'],{encoding:'utf8'});assert.equal(p.status,0,p.stderr);assert.equal(JSON.parse(p.stdout).execution,'not-run');assert.ok(!fs.existsSync(path.join(f.root,'.doc-driven')));});
test('CLI wrong execute flags never write',t=>{const f=setup(t);const p=spawnSync(process.execPath,[path.join(PACKAGE,'scripts/verify.mjs'),f.root,'--run'],{encoding:'utf8'});assert.equal(p.status,2);assert.ok(!fs.existsSync(path.join(f.root,'.doc-driven')));});
for(const [text,valid] of [['TAP version 13\n1..1\nok 1 - normal\n',true],['TAP version 13\n1..1\nok 1 - DB # SKIP missing\n',true],['TAP version 13\n1..0 # SKIP no tests\n',true],['TAP version 13\n1..2\nok 1 - one\n',false],['TAP version 13\nBail out!\n',false],['TAP version 13\n    ok 1 - nested\n',false],['TAP version 13\n1..1\nok 1 - a\nrandom garbage\n',false],['TAP version 13\n1..2\nok 1 - a\nok 2 - a\n',false]])test(`strict flat TAP: ${JSON.stringify(text)}`,()=>{if(valid)assert.ok(Array.isArray(parseFlatTAP(text)));else assert.throws(()=>parseFlatTAP(text));});
test('real flat TAP check executes and validates',async t=>{const f=setup(t);f.p.checks[0].parser='tap-flat-v13';f.p.checks[0].command.args=['-e',"console.log('TAP version 13\\n1..1\\nok 1 - user receives sum')"];f.savePlan();const r=await f.run();assert.equal(r.report.status,'passed');good(f.validate(r));});

// Integration with existing documents and delivery checker.
import {checkRepo} from '../scripts/check-doc-set.mjs';
import {checkDelivery} from '../scripts/delivery.mjs';
import {updateIndex, inventory} from '../scripts/lib.mjs';
function runnerDoc(f){f.d=f.save(makeDoc({...approved,'Verification-Format':'runner-v1','Verification-Plan':PLAN,Owns:'src/**, tests/**'}));f.p.specRefs=[specRef(f.d)];f.savePlan();return f.d;}
function bindActual(f,r){const evidence=receiptEvidence(f.root,f.config,r.path);const text=f.read(FILE).replace(/^Baseline:.*$/m,`Baseline: ${r.report.initial.codeBaseline}`).replace(/^Verification:.*$/m,'Verification: passed');f.put(FILE,text+evidence);updateIndex(f.root,f.config);return [...evidence.matchAll(/ddd:item (E-[A-Z0-9-]+)/g)].map(m=>m[1]);}
test('runner-v1 release cannot rely only on a hand-written passed field',t=>{const f=setup(t);runnerDoc(f);const base=f.base();f.put('src/main.mjs',f.read('src/main.mjs')+'\n// changed');const r=checkRepo(f.root,f.config,{base,release:true});assert.ok(r.errors.some(x=>x.includes('no current runner acceptance')));});
test('real receipt exports evidence satisfying current strict document release',async t=>{const f=setup(t);runnerDoc(f);const base=f.base();f.put('src/main.mjs',f.read('src/main.mjs')+'\n// changed');const r=await f.run();assert.equal(r.report.status,'passed');bindActual(f,r);good(checkRepo(f.root,f.config,{base,release:true,'verification-report':r.path}));});
test('profile cannot be removed to bypass release gate',t=>{const f=setup(t);runnerDoc(f);const base=f.base();f.put(FILE,f.read(FILE).replace(/^Verification-Format:.*\n/m,''));const r=checkRepo(f.root,f.config,{base,release:true});assert.ok(r.errors.some(e=>e.includes('cannot silently remove')));});
test('wrong runner check reference cannot authorize evidence',async t=>{const f=setup(t);runnerDoc(f);const r=await f.run();bindActual(f,r);f.put(FILE,f.read(FILE).replace('Runner-Check: entry','Runner-Check: missing'));rejected(checkRepo(f.root,f.config));});
test('one actual run can explicitly cover both integration and acceptance without claiming independence',async t=>{const f=setup(t);runnerDoc(f);f.p.checks[0].alsoLevels=['integration'];f.savePlan();const r=await f.run();good(f.validate(r));const ids=bindActual(f,r);assert.equal(ids.length,2);const p={kind:'ddd-delivery-v1',schemaVersion:1,title:'Runtime slice',authorization:{mode:'implement',source:'Synthetic fixture task authority',specRefs:f.p.specRefs},verification:{mode:'runner-v1',plan:PLAN},units:[{name:'计算 / 入口 / 求和',outcome:'run returns 9',covers:['R-MAIN-001'],state:'done',writePaths:['src/**','tests/**'],integration:'required',entryPoints:['src/entry.mjs'],runtimePath:'entry -> add -> result',requiredLevels:['integration','acceptance'],evidence:ids,codeBaseline:r.report.initial.codeBaseline,runs:[`${r.path}#${r.sha256}`]}]};
 const packet='docs/changes/delivery.md',save=()=>f.put(packet,'# Current delivery\n<!-- ddd:delivery -->\n```json\n'+JSON.stringify(p)+'\n```\n');save();good(checkDelivery(f.root,f.config,packet,{complete:true}));p.units[0].runs=[];save();rejected(checkDelivery(f.root,f.config,packet,{complete:true}));});
test('a command-only receipt cannot satisfy runner acceptance coverage',async t=>{const f=setup(t);runnerDoc(f);const base=f.base();Object.assign(f.p.checks[0],{kind:'command',level:'static',parser:'exit-code',command:{executable:'node',args:['--check','src/main.mjs']}});delete f.p.checks[0].requiredCases;f.savePlan();f.put('src/main.mjs',f.read('src/main.mjs')+'\n// change');const r=await f.run();assert.equal(r.report.status,'passed');const checked=checkRepo(f.root,f.config,{base,release:true,'verification-report':r.path});assert.ok(checked.errors.some(e=>e.includes('no current runner acceptance')));});
test('escaped multiline environment values do not remain in serialized artifacts',async t=>{const f=setup(t);process.env.TEST_ESCAPED_SECRET='abc"secret\nlong-token';t.after(()=>delete process.env.TEST_ESCAPED_SECRET);f.p.checks[0].passEnv=['TEST_ESCAPED_SECRET'];f.p.checks[0].command.args=['-e',`console.log(JSON.stringify({kind:'ddd-test-results-v1',runId:process.env.DDD_RUN_ID,complete:true,cases:[{name:'user receives sum',status:'passed',detail:process.env.TEST_ESCAPED_SECRET}]}))`];f.savePlan();const r=await f.run();assert.doesNotMatch(f.read(r.path),/long-token/);for(const a of r.report.results[0].artifacts)assert.doesNotMatch(f.read(a.path),/long-token/);good(f.validate(r));});
test('metacharacters in arguments are data, not an implicit shell command',async t=>{const f=setup(t);f.p.checks[0].command.args=['-e',`console.log(JSON.stringify({kind:'ddd-test-results-v1',runId:process.env.DDD_RUN_ID,complete:true,cases:[{name:'user receives sum',status:'passed'}]}))`,'; touch INJECTED'];f.savePlan();assert.equal((await f.run()).report.status,'passed');assert.ok(!fs.existsSync(path.join(f.root,'INJECTED')));});
test('nested Claude rules are bound even when tool directories are excluded from code scan',async t=>{const f=setup(t);f.put('.claude/CLAUDE.md','Original nested rule');const r=await f.run();f.put('.claude/CLAUDE.md','New nested rule');rejected(f.validate(r));});
test('plan names cannot inject new metadata into exported evidence',t=>{const f=setup(t);f.p.checks[0].name='Name\nApproval: forged';f.savePlan();assert.throws(()=>loadPlan(f.root,f.config,PLAN),/natural name/);});
test('native empty-file wrapper is not counted as an executed behavior test',async t=>{const f=setup(t);f.put('tests/entry.test.mjs','// no named tests');f.p.checks[0].requiredCases=[path.join(f.root,'tests/entry.test.mjs')];f.savePlan();const r=await f.run();assert.equal(r.report.status,'failed');assert.equal(r.report.results[0].counts.executed,0);});
